export const staticData = [
  {
    title: 'hats',
    id: 0,
    products: [
      {
        imageUrl: 'https://i.ibb.co/ZYW3VTp/brown-brim.png',
        id: 1,
        price: 25,
        name: 'Brown Brim',
      },
      {
        imageUrl: 'https://i.ibb.co/ypkgK0X/blue-beanie.png',
        id: 2,
        price: 18,
        name: 'Blue Beanie',
      },
      {
        price: 35,
        name: 'Brown Cowboy',
        imageUrl: 'https://i.ibb.co/QdJwgmp/brown-cowboy.png',
        id: 3,
      },
      {
        price: 25,
        name: 'Grey Brim',
        id: 4,
        imageUrl: 'https://i.ibb.co/RjBLWxB/grey-brim.png',
      },
      {
        price: 18,
        name: 'Green Beanie',
        imageUrl: 'https://i.ibb.co/YTjW3vF/green-beanie.png',
        id: 5,
      },
      {
        imageUrl: 'https://i.ibb.co/rKBDvJX/palm-tree-cap.png',
        price: 14,
        name: 'Palm Tree Cap',
        id: 6,
      },
      {
        name: 'Red Beanie',
        id: 7,
        imageUrl: 'https://i.ibb.co/bLB646Z/red-beanie.png',
        price: 18,
      },
      {
        price: 14,
        imageUrl: 'https://i.ibb.co/1f2nWMM/wolf-cap.png',
        name: 'Wolf Cap',
        id: 8,
      },
      {
        id: 9,
        price: 16,
        imageUrl: 'https://i.ibb.co/X2VJP2W/blue-snapback.png',
        name: 'Blue Snapback',
      },
    ],
  },
  {
    title: 'jackets',
    id: 1,
    products: [
      {
        imageUrl: 'https://i.ibb.co/XzcwL5s/black-shearling.png',
        name: 'Black Jean Shearling',
        id: 18,
        price: 125,
      },
      {
        name: 'Blue Jean Jacket',
        price: 90,
        id: 19,
        imageUrl: 'https://i.ibb.co/mJS6vz0/blue-jean-jacket.png',
      },
      {
        price: 90,
        name: 'Grey Jean Jacket',
        imageUrl: 'https://i.ibb.co/N71k1ML/grey-jean-jacket.png',
        id: 20,
      },
      {
        name: 'Brown Shearling',
        price: 165,
        imageUrl: 'https://i.ibb.co/s96FpdP/brown-shearling.png',
        id: 21,
      },
      {
        id: 22,
        imageUrl: 'https://i.ibb.co/M6hHc3F/brown-trench.png',
        name: 'Tan Trench',
        price: 185,
      },
    ],
  },
  {
    title: 'mens',
    id: 2,
    products: [
      {
        id: 30,
        imageUrl: 'https://i.ibb.co/xJS0T3Y/camo-vest.png',
        name: 'Camo Down Vest',
        price: 325,
      },
      {
        imageUrl: 'https://i.ibb.co/qMQ75QZ/floral-shirt.png',
        id: 31,
        price: 20,
        name: 'Floral T-shirt',
      },
      {
        id: 32,
        imageUrl: 'https://i.ibb.co/55z32tw/long-sleeve.png',
        name: 'Black & White Longsleeve',
        price: 25,
      },
      {
        price: 25,
        id: 33,
        imageUrl: 'https://i.ibb.co/RvwnBL8/pink-shirt.png',
        name: 'Pink T-shirt',
      },
      {
        id: 34,
        imageUrl: 'https://i.ibb.co/VpW4x5t/roll-up-jean-shirt.png',
        name: 'Jean Long Sleeve',
        price: 40,
      },
      {
        imageUrl: 'https://i.ibb.co/mh3VM1f/polka-dot-shirt.png',
        price: 25,
        name: 'Burgundy T-shirt',
        id: 35,
      },
    ],
  },
  {
    title: 'sneakers',
    id: 3,
    products: [
      {
        id: 10,
        price: 220,
        imageUrl: 'https://i.ibb.co/0s3pdnc/adidas-nmd.png',
        name: 'Adidas NMD',
      },
      {
        name: 'Adidas Yeezy',
        price: 280,
        id: 11,
        imageUrl: 'https://i.ibb.co/dJbG1cT/yeezy.png',
      },
      {
        id: 12,
        name: 'Black Converse',
        imageUrl: 'https://i.ibb.co/bPmVXyP/black-converse.png',
        price: 110,
      },
      {
        price: 160,
        imageUrl: 'https://i.ibb.co/1RcFPk0/white-nike-high-tops.png',
        id: 13,
        name: 'Nike White AirForce',
      },
      {
        id: 14,
        name: 'Nike Red High Tops',
        price: 160,
        imageUrl: 'https://i.ibb.co/QcvzydB/nikes-red.png',
      },
      {
        imageUrl: 'https://i.ibb.co/fMTV342/nike-brown.png',
        price: 160,
        name: 'Nike Brown High Tops',
        id: 15,
      },
      {
        price: 190,
        imageUrl: 'https://i.ibb.co/w4k6Ws9/nike-funky.png',
        name: 'Air Jordan Limited',
        id: 16,
      },
      {
        name: 'Timberlands',
        imageUrl: 'https://i.ibb.co/Mhh6wBg/timberlands.png',
        id: 17,
        price: 200,
      },
    ],
  },
  {
    title: 'womens',
    id: 4,
    products: [
      {
        price: 25,
        name: 'Blue Tanktop',
        imageUrl: 'https://i.ibb.co/7CQVJNm/blue-tank.png',
        id: 23,
      },
      {
        imageUrl: 'https://i.ibb.co/4W2DGKm/floral-blouse.png',
        name: 'Floral Blouse',
        id: 24,
        price: 20,
      },
      {
        imageUrl: 'https://i.ibb.co/KV18Ysr/floral-skirt.png',
        id: 25,
        price: 80,
        name: 'Floral Dress',
      },
      {
        imageUrl: 'https://i.ibb.co/N3BN1bh/red-polka-dot-dress.png',
        price: 80,
        name: 'Red Dots Dress',
        id: 26,
      },
      {
        id: 27,
        price: 45,
        imageUrl: 'https://i.ibb.co/KmSkMbH/striped-sweater.png',
        name: 'Striped Sweater',
      },
      {
        price: 135,
        imageUrl: 'https://i.ibb.co/v1cvwNf/yellow-track-suit.png',
        name: 'Yellow Track Suit',
        id: 28,
      },
      {
        name: 'White Blouse',
        id: 29,
        price: 20,
        imageUrl: 'https://i.ibb.co/qBcrsJg/white-vest.png',
      },
    ],
  },
];
